/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;//dùng cho DeafaultTableModel
import java.awt.event.MouseAdapter;
import javax.swing.JOptionPane;//alert message box
import java.awt.*;
import java.awt.event.*;//dùng khi click chuột
import java.util.List;
import java.util.ArrayList;

//su dung cho csdl
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author dungx
 */
public class CategoryJFrames extends javax.swing.JFrame {
    private static final String URL = "jdbc:mysql://localhost:3306/billiards";
    private static final String USER = "root";
    private static final String PASSWORD = "";
    private DefaultTableModel model;
    private int selectedRow = -1;//biến lưu dòng được chọn
    /**
     * Creates new form CategoryJFrames
     */
    public CategoryJFrames() {
        initComponents();
        model = (DefaultTableModel) tableCategory.getModel();
        //hiển thị danh sách sinh viên
        read();
        tableCategory.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseReleased(MouseEvent e){
                fillText();
            }       
        });
    }
    private void fillText(){
        selectedRow = tableCategory.getSelectedRow();
        if (selectedRow != -1){
            textCategoryName.setText(tableCategory.getValueAt(selectedRow,1).toString());
            textCategoryStatus.setText(tableCategory.getValueAt(selectedRow,2).toString());
        }   
    }
    //hàm hiển thị danh sách sinh viên
    public void read(){
        //clear toàn bộ dòng trong tableStudents
        model.setRowCount(0);
        //---
        String sql = "select * from category order by categoryID asc";
        try{
            Connection conn = DriverManager.getConnection(URL,USER,PASSWORD);
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            //đưa dữ liệu vào tableCategory
            while(rs.next()){
                model.addRow(new Object[]{ rs.getInt("categoryID"),rs.getString("categoryName"), rs.getString("status")});
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textCategoryName = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textCategoryStatus = new javax.swing.JTextArea();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCategory = new javax.swing.JTable();
        Detail_Service = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên dịch vụ");

        jLabel2.setText("Trạng thái");

        textCategoryName.setColumns(20);
        textCategoryName.setRows(5);
        jScrollPane1.setViewportView(textCategoryName);

        textCategoryStatus.setColumns(20);
        textCategoryStatus.setRows(5);
        jScrollPane2.setViewportView(textCategoryStatus);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        tableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID loại dịch vụ", "Tên loại dịch vụ", "Trạng thái"
            }
        ));
        jScrollPane3.setViewportView(tableCategory);

        Detail_Service.setText("Xem chi tiết dịch vụ");
        Detail_Service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detail_ServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Detail_Service)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(Add)
                            .addGap(48, 48, 48)
                            .addComponent(Update)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                            .addComponent(Delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Detail_Service)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        Delete();
    }//GEN-LAST:event_DeleteActionPerformed
    private void Delete() {
        selectedRow = tableCategory.getSelectedRow();

        // Kiểm tra xem có dòng nào được chọn không
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn danh mục cần xóa!");
            return;
        }

        // Lấy categoryId từ bảng (giả sử cột 0 chứa categoryId)
        int categoryId = Integer.parseInt(tableCategory.getValueAt(selectedRow, 0).toString());

        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn xóa danh mục này và tất cả các dịch vụ liên quan?", 
            "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        Connection conn = null;
        PreparedStatement stmt1 = null;
        PreparedStatement stmt2 = null;

        try {
            conn = DriverManager.getConnection(URL,USER,PASSWORD);
            conn.setAutoCommit(false); // Bắt đầu transaction

            // Xóa tất cả các dịch vụ (service) có categoryId trùng
            String deleteServicesSQL = "DELETE FROM serviceitem WHERE categoryID = ?";
            stmt1 = conn.prepareStatement(deleteServicesSQL);
            stmt1.setInt(1, categoryId);
            stmt1.executeUpdate();

            // Xóa danh mục (category)
            String deleteCategorySQL = "DELETE FROM category WHERE categoryID = ?";
            stmt2 = conn.prepareStatement(deleteCategorySQL);
            stmt2.setInt(1, categoryId);
            int rowsDeleted = stmt2.executeUpdate();

            if (rowsDeleted > 0) {
                conn.commit(); // Xác nhận transaction
                JOptionPane.showMessageDialog(this, "Xóa danh mục và tất cả dịch vụ liên quan thành công!");
                loadCategoryTable(); // Cập nhật lại bảng danh mục
                textCategoryName.setText("");
                textCategoryStatus.setText("");
            } else {
                conn.rollback();
                JOptionPane.showMessageDialog(this, "Xóa thất bại. Vui lòng thử lại.");
            }

        } catch (SQLException e) {
            if (conn != null) {
                try {
                    conn.rollback(); // Hoàn tác nếu có lỗi
                } catch (SQLException rollbackEx) {
                    rollbackEx.printStackTrace();
                }
            }
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa danh mục: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (stmt1 != null) stmt1.close();
                if (stmt2 != null) stmt2.close();
                if (conn != null) conn.close();
            } catch (SQLException closeEx) {
                closeEx.printStackTrace();
            }
        }
    }
    private void loadCategoryTable() {
        DefaultTableModel model = (DefaultTableModel) tableCategory.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ trước khi cập nhật mới

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection(URL,USER,PASSWORD);
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM category"); // Lấy danh sách danh mục từ database

            while (rs.next()) {
                int id = rs.getInt("categoryID");
                String name = rs.getString("categoryName");
                String status = rs.getString("status");
                model.addRow(new Object[]{id, name,status}); // Thêm vào bảng
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải danh mục: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }



//    public void Delete() {
//        selectedRow = tableCategory.getSelectedRow();
//        if (selectedRow == -1) {
//            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
//        if (confirm != JOptionPane.YES_OPTION) {
//            return;
//        }
//
//        try {
//            // Lấy ID của hàng đã chọn
//            int categoryId = (int) tableCategory.getValueAt(selectedRow, 0);
//        
//            Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
//            PreparedStatement stmt = conn.prepareStatement("DELETE FROM category WHERE categoryID = ?");
//            stmt.setInt(1, categoryId);
//        
//            int affectedRows = stmt.executeUpdate();
//            if (affectedRows > 0) {
//                JOptionPane.showMessageDialog(this, "Đã xóa thành công");
//            
//                // Xóa dòng khỏi tableCategory
//                DefaultTableModel model = (DefaultTableModel) tableCategory.getModel();
//                model.removeRow(selectedRow);
//            
//                // Xóa dữ liệu hiển thị trên text field
//                textCategoryName.setText("");
//                textCategoryStatus.setText("");
//            } 
//            else {
//                JOptionPane.showMessageDialog(this, "Xóa thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            }
//            stmt.close();
//            conn.close();
//        } 
//        catch (SQLException e) {
//            e.printStackTrace();
//        }
//    }
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:;
        Create();
    }//GEN-LAST:event_AddActionPerformed
    public void Create() {
        String _textCategoryName = textCategoryName.getText().trim();
        String _textCategoryStatus = textCategoryStatus.getText().trim();

        if (_textCategoryName.isEmpty() || _textCategoryStatus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn cần điền đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);

            // Kiểm tra categoryName đã tồn tại chưa
            PreparedStatement checkStmt = conn.prepareStatement("SELECT COUNT(*) FROM category WHERE categoryName = ?");
            checkStmt.setString(1, _textCategoryName);
            ResultSet rs = checkStmt.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            rs.close();
            checkStmt.close();

            if (count > 0) {
                JOptionPane.showMessageDialog(this, "Đã có loại dịch vụ này!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                // Thêm mới nếu không trùng
                PreparedStatement stmt = conn.prepareStatement("INSERT INTO category (categoryName, status) VALUES (?, ?)");
                stmt.setString(1, _textCategoryName);
                stmt.setString(2, _textCategoryStatus);
                int effectedRows = stmt.executeUpdate();
                stmt.close();

                if (effectedRows > 0) {
                    JOptionPane.showMessageDialog(this, "Đã thêm bản ghi thành công");
                    read(); // Cập nhật lại bảng
                    textCategoryName.setText("");
                    textCategoryStatus.setText("");
                }
            }
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_UpdateActionPerformed
    public void Update(){
        selectedRow = tableCategory.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để cập nhật", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String _textCategoryName = textCategoryName.getText();
        String _textCategoryStatus = textCategoryStatus.getText();

        if (_textCategoryName.isEmpty() || _textCategoryStatus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn cần điền đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } 
        else {
            try {
                // Lấy ID của hàng đã chọn
                int categoryId = (int) tableCategory.getValueAt(selectedRow, 0);

                Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
                PreparedStatement stmt = conn.prepareStatement("UPDATE category SET categoryName = ?, status = ? WHERE categoryID = ?");
                
                // Truyền các giá trị vào dấu ?
                stmt.setString(1, _textCategoryName);
                stmt.setString(2, _textCategoryStatus);
                stmt.setInt(3, categoryId);

                int effectedRows = stmt.executeUpdate();
                if (effectedRows > 0) {
                    JOptionPane.showMessageDialog(this, "Đã cập nhật thành công");
                    // Gọi lại hàm Read để đổ dữ liệu mới vào bảng
                    read();
                    textCategoryName.setText("");
                    textCategoryStatus.setText("");
                } 
                else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                stmt.close();
                conn.close();
            } 
            catch (SQLException e) {
                e.printStackTrace();
            }
        }       
    }
    private void Detail_ServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detail_ServiceActionPerformed
        // TODO add your handling code here:
        Detail();
    }//GEN-LAST:event_Detail_ServiceActionPerformed
    public void Detail() {
        int selectedRow = tableCategory.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để cập nhật", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy categoryId từ dòng được chọn
        int categoryId = (int) tableCategory.getValueAt(selectedRow, 0);

        // Khởi tạo ServiceDetailJFrame với categoryId đã lấy được
        ServiceDetailJFrame serviceDetailFrame = new ServiceDetailJFrame(categoryId);

        // Hiển thị cửa sổ ServiceDetailJFrame
        serviceDetailFrame.setVisible(true);
    }

    //public void Detail(){
//        selectedRow = tableCategory.getSelectedRow();
//        if (selectedRow == -1) {
//            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để cập nhật", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            return;
//        } else {
//            int categoryId = (int) tableCategory.getValueAt(selectedRow, 0);
//            try {
//                Connection conn = DriverManager.getConnection(URL, USER, PASSWORD);
//                PreparedStatement stmt = conn.prepareStatement("SELECT * FROM serviceitem WHERE categoryId = ?");
//                stmt.setInt(1, categoryId);
//                ResultSet rs = stmt.executeQuery();
//                DefaultTableModel model = (DefaultTableModel) tableCategory.getModel();
//                model.setRowCount(0); // Xóa dữ liệu cũ
//                boolean hasData = false;
//                while (rs.next()) {
//                    int serviceId = rs.getInt("serviceID");
//                    String serviceName = rs.getString("serviceName");
//                    String price = rs.getString("price");
//                    String unit = rs.getString("unit");
//                    int stock = rs.getInt("stock");
//                    model.addRow(new Object[]{serviceId, serviceName,price,unit,stock});
//                    hasData = true;
//                }
//                
//                if (!hasData) {
//                    JOptionPane.showMessageDialog(this, "Không có dịch vụ nào trong danh mục này", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
//                    read();
//                }
//
//                rs.close();
//                stmt.close();
//                conn.close();
//            } catch (SQLException ex) {
//                Logger.getLogger(CategoryJFrames.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryJFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Detail_Service;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableCategory;
    private javax.swing.JTextArea textCategoryName;
    private javax.swing.JTextArea textCategoryStatus;
    // End of variables declaration//GEN-END:variables
}
